import * as MetadataType from './metadataTypes.js';

export const ALL_METADATA_TYPES = [
  MetadataType.APEX_CLASS,
  MetadataType.APEX_TRIGGER,
  MetadataType.APEX_PAGE,
  MetadataType.APEX_COMPONENT,
  MetadataType.AURA_COMPONENT,
  MetadataType.COMPACT_LAYOUT,
  MetadataType.CUSTOM_FIELD,
  MetadataType.CUSTOM_OBJECT,
  MetadataType.CUSTOM_TAB,
  MetadataType.FLEXIPAGE,
  MetadataType.FIELD_SET,
  MetadataType.FLOW,
  MetadataType.LAYOUT,
  MetadataType.LIGHTNING_WEB_COMPONENT,
  MetadataType.LIST_VIEW,
  MetadataType.PERMISSION_SET,
  MetadataType.PERMISSION_SET_GROUP,
  MetadataType.PROFILE,
  MetadataType.QUICK_ACTION,
  MetadataType.RECORD_TYPE,
  MetadataType.ROLE,
  MetadataType.USER_ACCESS_POLICY,
  MetadataType.VALIDATION_RULE,
  MetadataType.WEBLINK,
  MetadataType.WORKFLOW,
  MetadataType.WORKFLOW_RULE,
];
