import { Table } from '../tables.js';
import { CUSTOM_FIELD } from '../../../metadataReader/metadataTypes.js';

export const FIELDS: Table = {
  name: 'Fields',
  definition: CUSTOM_FIELD,
  columns: [
    { title: 'Object', id: 'objectName' },
    { title: 'Name', id: 'name' },
    { title: 'Full Name', id: 'fullName' },
    { title: 'Label', id: 'label' },
    { title: 'Type', id: 'type' },
    { title: 'Required', id: 'required' },
    { title: 'Unique', id: 'unique' },
    { title: 'External ID', id: 'externalId' },
    { title: 'AI Prediction Field', id: 'isAIPredictionField' },
    { title: 'Case Sensitive', id: 'caseSensitive' },
    { title: 'Encryption Scheme (Shield)', id: 'encryptionScheme' },
    { title: 'Masking Type (Classic)', id: 'maskType' },
    { title: 'Masking Character (Classic)', id: 'maskChar' },
    { title: 'Description', id: 'description' },
    { title: 'Help Text', id: 'inlineHelpText' },
    { title: 'Default Value', id: 'defaultValue' },
    { title: 'Length', id: 'length' },
    { title: 'Visible Lines', id: 'visibleLines' },
    { title: 'Precision', id: 'precision' },
    { title: 'Scale', id: 'scale' },
    { title: 'Value Set', id: 'valueSet' },
    { title: 'Formula', id: 'formula' },
    { title: 'Treat Formula Blanks As', id: 'formulaTreatBlanksAs' },
    { title: 'Reference To', id: 'referenceTo' },
    { title: 'Relationship Name', id: 'relationshipName' },
    { title: 'Relationship Label', id: 'relationshipLabel' },
    { title: 'Relationship Order', id: 'relationshipOrder' },
    { title: 'Lookup Filter', id: 'lookupFilter' },
    { title: 'Delete Constraint', id: 'deleteConstraint' },
    { title: 'Reparentable Master Detail', id: 'reparentableMasterDetail' },
    { title: 'Write Requires Master Read', id: 'writeRequiresMasterRead' },
    { title: 'Summary Operation', id: 'summaryOperation' },
    { title: 'Summarized Field', id: 'summarizedField' },
    { title: 'Summary Filter Items', id: 'summaryFilterItems' },
    { title: 'Track Feed History', id: 'trackFeedHistory' },
    { title: 'Track History', id: 'trackHistory' },
    { title: 'Track Trending', id: 'trackTrending' },
    { title: 'Security Classification', id: 'securityClassification' },
    { title: 'Compliance Group', id: 'complianceGroup' },
    { title: 'Business Owner Group', id: 'businessOwnerGroup' },
    { title: 'Business Owner User', id: 'businessOwnerUser' },
    { title: 'Business Status', id: 'businessStatus' },
  ],
};
